// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CPU struct {
	ID         string   `json:"id"`
	Marca      *string  `json:"marca"`
	Modelo     *string  `json:"modelo"`
	Nucleos    *int     `json:"nucleos"`
	MaxRAM     *int     `json:"maxRam"`
	Velocidade *string  `json:"velocidade"`
	Tdp        *float64 `json:"tdp"`
}

type Camera struct {
	ID     string  `json:"id"`
	Marca  *string `json:"marca"`
	Modelo string  `json:"modelo"`
}

type Computador struct {
	ID            string              `json:"id"`
	Nome          string              `json:"nome"`
	Info          *Informacao         `json:"info"`
	Conectividade *Conectividade      `json:"conectividade"`
	Equipamento   *HardwareInterno    `json:"equipamento"`
	Hardware      *ListaHardware      `json:"hardware"`
	Perifericos   *EquipamentoExterno `json:"perifericos"`
	Software      []*Software         `json:"software"`
}

type Conectividade struct {
	Ethernet         *bool `json:"ethernet"`
	Wifi             *bool `json:"wifi"`
	ConectadoDominio *bool `json:"conectadoDominio"`
}

type ConexoesMBoard struct {
	Sata     *int `json:"sata"`
	Pcie4_16 *int `json:"pcie4_16"`
	Pcie3_16 *int `json:"pcie3_16"`
}

type EquipamentoExterno struct {
	Camera    []*Camera    `json:"camera"`
	Microfone []*Microfone `json:"microfone"`
}

type Gpu struct {
	ID         string   `json:"id"`
	Marca      *string  `json:"marca"`
	Modelo     *string  `json:"modelo"`
	Vram       *string  `json:"vram"`
	Velocidade *string  `json:"velocidade"`
	Saidas     *string  `json:"saidas"`
	Tdp        *float64 `json:"tdp"`
}

type HardwareInterno struct {
	CPUUtil       *string `json:"cpuUtil"`
	GpuUtil       *string `json:"gpuUtil"`
	RAMSlots      *int    `json:"ramSlots"`
	RAMTipo       *string `json:"ramTipo"`
	RAMVelocidade *string `json:"ramVelocidade"`
	RAMMemoria    string  `json:"ramMemoria"`
}

type Informacao struct {
	SalaAtribuida    *string `json:"salaAtribuida"`
	UltimaInspecao   *string `json:"ultimaInspecao"`
	TipoPc           *string `json:"tipoPc"`
	Utilisacao       *string `json:"utilisacao"`
	TipoUtilisacao   *string `json:"tipoUtilisacao"`
	Dominio          *string `json:"dominio"`
	SistemaOperativo *string `json:"sistemaOperativo"`
}

type InterfacesMBoard struct {
	Usb2    *int  `json:"usb2"`
	Usb3    *int  `json:"usb3"`
	Lan     *bool `json:"lan"`
	Display *int  `json:"display"`
	Hdmi    *int  `json:"hdmi"`
	Audio   *int  `json:"audio"`
	Wifi    *int  `json:"wifi"`
}

type Item struct {
	ID        string  `json:"id"`
	Marca     *string `json:"marca"`
	Modelo    *string `json:"modelo"`
	Nome      string  `json:"nome"`
	PaginaWeb *string `json:"paginaWeb"`
}

type ListaHardware struct {
	CPU    *CPU    `json:"cpu"`
	Gpu    *Gpu    `json:"gpu"`
	RAM    []*RAM  `json:"ram"`
	PlacaM *MBoard `json:"placaM"`
}

type MBoard struct {
	ID                string            `json:"id"`
	Marca             *string           `json:"marca"`
	Modelo            *string           `json:"modelo"`
	TipoMemoria       *string           `json:"tipoMemoria"`
	Chipset           *string           `json:"chipset"`
	FamiliaCompativel *string           `json:"familiaCompativel"`
	Socket            *string           `json:"socket"`
	DimSlots          *int              `json:"dimSlots"`
	DimMaxMem         *int              `json:"dimMaxMem"`
	DimMemType        *string           `json:"dimMemType"`
	DimMaxVelc        *string           `json:"dimMaxVelc"`
	Conexoes          *ConexoesMBoard   `json:"conexoes"`
	Interfaces        *InterfacesMBoard `json:"interfaces"`
}

type Microfone struct {
	ID     string  `json:"id"`
	Marca  *string `json:"marca"`
	Modelo string  `json:"modelo"`
}

type NovoCPU struct {
	Marca      *string  `json:"marca"`
	Modelo     string   `json:"modelo"`
	Nucleos    *int     `json:"nucleos"`
	MaxRAM     *int     `json:"maxRam"`
	Velocidade *string  `json:"velocidade"`
	Tdp        *float64 `json:"tdp"`
}

type NovoComputador struct {
	Nome     string  `json:"nome"`
	Conteudo *string `json:"conteudo"`
}

type NovoGpu struct {
	Marca      *string  `json:"marca"`
	Modelo     *string  `json:"modelo"`
	Vram       *string  `json:"vram"`
	Velocidade *string  `json:"velocidade"`
	Saidas     *string  `json:"saidas"`
	Tdp        *float64 `json:"tdp"`
}

type NovoItem struct {
	Marca     *string `json:"marca"`
	Modelo    string  `json:"modelo"`
	Nome      *string `json:"nome"`
	PaginaWeb *string `json:"paginaWeb"`
}

type NovoRAM struct {
	Marca      *string `json:"marca"`
	Modelo     *string `json:"modelo"`
	Memoria    *string `json:"memoria"`
	Velocidade *string `json:"velocidade"`
	Tipo       *string `json:"tipo"`
}

type RAM struct {
	ID         string  `json:"id"`
	Marca      *string `json:"marca"`
	Modelo     *string `json:"modelo"`
	Memoria    *string `json:"memoria"`
	Velocidade *string `json:"velocidade"`
	Tipo       *string `json:"tipo"`
}

type Software struct {
	Nome string  `json:"nome"`
	Tipo *string `json:"tipo"`
}

type UpdateComputador struct {
	Nome         string `json:"nome"`
	NovoConteudo string `json:"novoConteudo"`
}
