// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CPU struct {
	ID         string   `json:"id"`
	Marca      *string  `json:"marca"`
	Modelo     *string  `json:"modelo"`
	Nucleos    *int     `json:"nucleos"`
	MaxRAM     *int     `json:"maxRam"`
	Velocidade *string  `json:"velocidade"`
	Tdp        *float64 `json:"tdp"`
}

type Camera struct {
	ID     string  `json:"id"`
	Marca  *string `json:"marca"`
	Modelo string  `json:"modelo"`
}

type ComponenteApagado struct {
	ID     string  `json:"id"`
	Modelo *string `json:"modelo"`
	Marca  *string `json:"marca"`
}

type ComponenteAtualizado struct {
	ID          string  `json:"id"`
	Modelo      *string `json:"modelo"`
	Atualizacao *string `json:"atualizacao"`
}

type ComponenteCriado struct {
	ID             string  `json:"id"`
	TipoComponente string  `json:"tipoComponente"`
	Modelo         *string `json:"modelo"`
}

type Computador struct {
	ID            *string             `json:"id"`
	Nome          *string             `json:"nome"`
	Info          *Informacao         `json:"info"`
	Conectividade *Conectividade      `json:"conectividade"`
	Equipamento   *HardwareInterno    `json:"equipamento"`
	Hardware      *ListaHardware      `json:"hardware"`
	Perifericos   *EquipamentoExterno `json:"perifericos"`
	Software      []*Software         `json:"software"`
}

type ComputadorAtualizado struct {
	ID          string  `json:"id"`
	Nome        *string `json:"nome"`
	Atualizacao *string `json:"atualizacao"`
}

type ComputadorCriado struct {
	ID   string  `json:"id"`
	Nome *string `json:"nome"`
}

type Conectividade struct {
	Ethernet         *bool `json:"ethernet"`
	Wifi             *bool `json:"wifi"`
	ConectadoDominio *bool `json:"conectadoDominio"`
}

type ConexoesMBoard struct {
	Sata     *int `json:"sata"`
	Pcie4_16 *int `json:"pcie4_16"`
	Pcie3_16 *int `json:"pcie3_16"`
}

type EquipamentoExterno struct {
	Camera    []*Camera    `json:"camera"`
	Microfone []*Microfone `json:"microfone"`
}

type Gpu struct {
	ID         string   `json:"id"`
	Marca      *string  `json:"marca"`
	Modelo     *string  `json:"modelo"`
	Vram       *string  `json:"vram"`
	Velocidade *string  `json:"velocidade"`
	Saidas     *string  `json:"saidas"`
	Tdp        *float64 `json:"tdp"`
}

type HardwareInterno struct {
	CPUUtil       *string `json:"cpuUtil"`
	GpuUtil       *string `json:"gpuUtil"`
	RAMSlots      *int    `json:"ramSlots"`
	RAMTipo       *string `json:"ramTipo"`
	RAMVelocidade *string `json:"ramVelocidade"`
	RAMMemoria    *string `json:"ramMemoria"`
}

type Informacao struct {
	SalaAtribuida    *string `json:"salaAtribuida"`
	UltimaInspecao   *string `json:"ultimaInspecao"`
	TipoPc           *string `json:"tipoPc"`
	Utilisacao       *string `json:"utilisacao"`
	TipoUtilisacao   *string `json:"tipoUtilisacao"`
	Dominio          *string `json:"dominio"`
	SistemaOperativo *string `json:"sistemaOperativo"`
}

type InputConectividade struct {
	Ethernet         *bool `json:"ethernet"`
	Wifi             *bool `json:"wifi"`
	ConectadoDominio *bool `json:"conectadoDominio"`
}

type InputEquipamentoExterno struct {
	Camera    []*NovaCamera    `json:"camera"`
	Microfone []*NovoMicrofone `json:"microfone"`
}

type InputHardwareInterno struct {
	CPUUtil       *string `json:"cpuUtil"`
	GpuUtil       *string `json:"gpuUtil"`
	RAMSlots      *int    `json:"ramSlots"`
	RAMTipo       *string `json:"ramTipo"`
	RAMVelocidade *string `json:"ramVelocidade"`
	RAMMemoria    *string `json:"ramMemoria"`
}

type InputInformacao struct {
	SalaAtribuida    *string `json:"salaAtribuida"`
	UltimaInspecao   *string `json:"ultimaInspecao"`
	TipoPc           *string `json:"tipoPc"`
	Utilisacao       *string `json:"utilisacao"`
	TipoUtilisacao   *string `json:"tipoUtilisacao"`
	Dominio          *string `json:"dominio"`
	SistemaOperativo *string `json:"sistemaOperativo"`
}

type InputListaHardware struct {
	CPU           *NovoCPU     `json:"cpu"`
	Gpu           *NovoGpu     `json:"gpu"`
	RAM           []*NovoRAM   `json:"ram"`
	PlacaM        *NovaMBoard  `json:"placaM"`
	Armazenamento *NovoStorage `json:"armazenamento"`
}

type InterfacesMBoard struct {
	Usb2    *int  `json:"usb2"`
	Usb3    *int  `json:"usb3"`
	Lan     *bool `json:"lan"`
	Display *int  `json:"display"`
	Hdmi    *int  `json:"hdmi"`
	Audio   *int  `json:"audio"`
	Wifi    *int  `json:"wifi"`
}

type Item struct {
	ID        *string `json:"id"`
	Marca     *string `json:"marca"`
	Modelo    *string `json:"modelo"`
	Nome      *string `json:"nome"`
	PaginaWeb *string `json:"paginaWeb"`
}

type ItemAtualizado struct {
	ID          string  `json:"id"`
	Nome        string  `json:"nome"`
	Modelo      *string `json:"modelo"`
	Atualizacao *string `json:"atualizacao"`
}

type ItemCriado struct {
	ID   string  `json:"id"`
	Nome *string `json:"nome"`
}

type ListaHardware struct {
	CPU           *CPU     `json:"cpu"`
	Gpu           *Gpu     `json:"gpu"`
	RAM           []*RAM   `json:"ram"`
	PlacaM        *MBoard  `json:"placaM"`
	Armazenamento *Storage `json:"armazenamento"`
}

type MBoard struct {
	ID                string            `json:"id"`
	Marca             *string           `json:"marca"`
	Modelo            *string           `json:"modelo"`
	TipoMemoria       *string           `json:"tipoMemoria"`
	Chipset           *string           `json:"chipset"`
	FamiliaCompativel *string           `json:"familiaCompativel"`
	Socket            *string           `json:"socket"`
	DimSlots          *int              `json:"dimSlots"`
	DimMaxMem         *int              `json:"dimMaxMem"`
	DimMemType        *string           `json:"dimMemType"`
	DimMaxVelc        *string           `json:"dimMaxVelc"`
	Conexoes          *ConexoesMBoard   `json:"conexoes"`
	Interfaces        *InterfacesMBoard `json:"interfaces"`
}

type Microfone struct {
	ID     string  `json:"id"`
	Marca  *string `json:"marca"`
	Modelo string  `json:"modelo"`
}

type NovaCamera struct {
	ID     *string `json:"id"`
	Marca  *string `json:"marca"`
	Modelo string  `json:"modelo"`
}

type NovaMBoard struct {
	ID                *string `json:"id"`
	Marca             *string `json:"marca"`
	Modelo            *string `json:"modelo"`
	TipoMemoria       *string `json:"tipoMemoria"`
	Chipset           *string `json:"chipset"`
	FamiliaCompativel *string `json:"familiaCompativel"`
	Socket            *string `json:"socket"`
	DimSlots          *int    `json:"dimSlots"`
	DimMaxMem         *int    `json:"dimMaxMem"`
	DimMemType        *string `json:"dimMemType"`
	DimMaxVelc        *string `json:"dimMaxVelc"`
	Conexoes          *string `json:"conexoes"`
	Interfaces        *string `json:"interfaces"`
}

type NovoCPU struct {
	ID         *string  `json:"id"`
	Marca      *string  `json:"marca"`
	Modelo     string   `json:"modelo"`
	Nucleos    *int     `json:"nucleos"`
	MaxRAM     *int     `json:"maxRam"`
	Velocidade *string  `json:"velocidade"`
	Tdp        *float64 `json:"tdp"`
}

type NovoComputador struct {
	ID            *string                  `json:"id"`
	Nome          string                   `json:"nome"`
	Info          *InputInformacao         `json:"info"`
	Conectividade *InputConectividade      `json:"conectividade"`
	Equipamento   *InputHardwareInterno    `json:"equipamento"`
	Hardware      *InputListaHardware      `json:"hardware"`
	Perifericos   *InputEquipamentoExterno `json:"perifericos"`
	Software      []*NovoSoftware          `json:"software"`
}

type NovoGpu struct {
	ID         *string  `json:"id"`
	Marca      *string  `json:"marca"`
	Modelo     *string  `json:"modelo"`
	Vram       *string  `json:"vram"`
	Velocidade *string  `json:"velocidade"`
	Saidas     *string  `json:"saidas"`
	Tdp        *float64 `json:"tdp"`
}

type NovoItem struct {
	ID        *string `json:"id"`
	Marca     *string `json:"marca"`
	Modelo    string  `json:"modelo"`
	Nome      *string `json:"nome"`
	PaginaWeb *string `json:"paginaWeb"`
}

type NovoMicrofone struct {
	ID     *string `json:"id"`
	Marca  *string `json:"marca"`
	Modelo string  `json:"modelo"`
}

type NovoRAM struct {
	ID         *string `json:"id"`
	Marca      *string `json:"marca"`
	Modelo     *string `json:"modelo"`
	Memoria    *string `json:"memoria"`
	Velocidade *string `json:"velocidade"`
	Tipo       *string `json:"tipo"`
}

type NovoSoftware struct {
	ID   *string `json:"id"`
	Nome string  `json:"nome"`
	Tipo *string `json:"tipo"`
}

type NovoStorage struct {
	ID         *string `json:"id"`
	Tipo       *string `json:"tipo"`
	Nome       *string `json:"nome"`
	Modelo     *string `json:"modelo"`
	Marca      *string `json:"marca"`
	Velocidade *string `json:"velocidade"`
	Capacidade *string `json:"capacidade"`
}

type RAM struct {
	ID         string  `json:"id"`
	Marca      *string `json:"marca"`
	Modelo     *string `json:"modelo"`
	Memoria    *string `json:"memoria"`
	Velocidade *string `json:"velocidade"`
	Tipo       *string `json:"tipo"`
}

type RegistoApagado struct {
	ID   string  `json:"id"`
	Nome *string `json:"nome"`
}

type Software struct {
	Nome string  `json:"nome"`
	Tipo *string `json:"tipo"`
}

type SoftwareAtualizado struct {
	ID          string  `json:"id"`
	Nome        *string `json:"nome"`
	Atualizacao *string `json:"atualizacao"`
}

type SoftwareCriado struct {
	ID   string  `json:"id"`
	Nome *string `json:"nome"`
}

type Storage struct {
	ID         string  `json:"id"`
	Tipo       *string `json:"tipo"`
	Nome       *string `json:"nome"`
	Marca      *string `json:"marca"`
	Velocidade *string `json:"velocidade"`
	Capacidade *string `json:"capacidade"`
}
